import React from 'react'

import '../styles/global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-900 flex items-center justify-center h-screen">
        {children}
      </body>
    </html>
  )
}
